CC=diet gcc
CFLAGS=-nostdinc
RESEARCH=/home/jcmarsh/research
LIBCDIR=$(RESEARCH)/dietlibc-0.33/bin-i386
PLAYER=$(RESEARCH)/player
SRCDIR=$(RESEARCH)/static_libplayerc
INC=-I$(SRCDIR)/ -I$(SRCDIR)/player_build/ -I$(SRCDIR)/player_build/libplayerinterface/ -I$(SRCDIR)/player_include/
