CC=diet gcc -nostdinc
LIBCDIR=/usr/lib/diet/lib-x86_64
RESEARCH=/home/jcmarsh/research
PLAYER=$(RESEARCH)/player
SRCDIR=$(RESEARCH)/static_libplayerc
INC=-I$(SRCDIR)/ -I$(SRCDIR)/player_build/ -I$(SRCDIR)/player_build/libplayerinterface/ -I$(SRCDIR)/player_include/
