include ../Makefile.variable

all: error.o

error.o:
#	gcc $(INC) -c -o error.o error.c


copy:
#	cp $(PLAYER)/client_libs/libplayerc/playerc.h ./
#	cp $(PLAYER)/client_libs/libplayerc/mclient.c ./
#	cp $(PLAYER)/client_libs/libplayerc/device.c ./

clean:
#	rm *.o

nuke:
#	rm -f *.c
#	rm -f *.h
